repos:
  - repo: local
    hooks:
      - id: black
        name: Code Formatting Step
        entry: black .
        language: python
        types: [python]

      - id: isort
        name: Sort Imports Step
        entry: isort .
        language: python
        types: [python]

      - id: flake8
        name: Style Guide Enforcement Step
        entry: flake8 .
        language: python
        types: [python]

      - id: unittest
        name: Unit Testing Step
        entry: python3 -m unittest discover 
        language: system
        types: [python]
        additional_dependencies: []
        pass_filenames: false
