repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort .
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8 .
        language: python
        types: [python]

      - id: unittest
        name: unittest
        entry: python3 -m unittest discover 
        language: system
        types: [python]
        additional_dependencies: []
        pass_filenames: false
